version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-sec_extractor}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DJANGO_ENV=development
      - DB_NAME=${DB_NAME:-sec_extractor}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  celery_worker:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - media_data:/app/media
    depends_on:
      - redis
      - db
    environment:
      - DEBUG=True
      - DJANGO_ENV=development
      - DB_NAME=${DB_NAME:-sec_extractor}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1
    command: celery -A sec_extractor worker -l info

  celery_beat:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DEBUG=True
      - DJANGO_ENV=development
      - DB_NAME=${DB_NAME:-sec_extractor}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1
    command: celery -A sec_extractor beat -l info

volumes:
  postgres_data:
  redis_data:
  media_data: 